import { ThemePreset, accentDerived } from '../theme-sync';

const popoverUniverse: ThemePreset = {
  id: 'popover-universe',
  name: 'Popover Universe',
  description: 'Neon sci-fi glows — deep black with electric cyan and violet.',
  colors: ['#00f5ff', '#bf00ff', '#ff00aa'],
  overrides: {
    '--ftr10-accent-1': '#00f5ffd4',
    '--ftr10-accent-2': '#bf00ff',
    '--ftr10-accent-3': '#ff00aa',
    '--ftr10-accent-4': '#7de8ff',
    '--ftr10-accent-5': '#d97fff',
    '--ftr10-cyan': '#00f5ff',
    '--ftr10-purple': '#bf00ff',
    '--ftr10-cursor': '#7de8ff',
    '--ftr10-tab-border-color': '#00f5ff',
    '--ftr10-surface-1': '#00f5ff26',
    '--ftr10-bg': '#0a0a0fff',
    '--ftr10-bg-editor': '#0a0a0fff',
    '--ftr10-text': '#ffffffe6',
    '--ftr10-text-muted': '#ffffff73',
    '--ftr10-border': '#00f5ff1f',
    '--ftr10-body-font': "'Victor Mono', monospace",
    '--ftr10-heading-font': "'Orbitron', 'Victor Mono', monospace",
    '--ftr10-code-font': "'Victor Mono', monospace",
    '--ftr10-font-activitybar': "'Orbitron', monospace",
    '--ftr10-font-sidebar': "'Victor Mono', monospace",
    '--ftr10-font-panel-bottom': "'Orbitron', monospace",
    '--ftr10-font-panel-top': "'JetBrains Mono', monospace",
    '--ftr10-font-auxiliarybar': "'Victor Mono', monospace",
    '--ftr10-heading-transform': 'uppercase',
    '--ftr10-heading-spacing': '2px',
    '--ftr10-radius-block': '3px',
    '--ftr10-radius-quote': '3px',
    '--ftr10-radius-inline': '2px',
    '--ftr10-radius-img': '4px',
    '--ftr10-strong-color': '#00f5ff',
    '--ftr10-em-color': '#00f5ff',
    '--ftr10-mark-bg': '#00f5ff1a',
    '--ftr10-mark-color': '#00f5ff',
    '--ftr10-link-style': 'dashed',
    '--ftr10-surface-hover': '#00f5ff0f',
    '--ftr10-blockquote-width': '2px',
    '--ftr10-code-scanline': '#00f5ff06',
    '--ftr10-tab-gradient': 'linear-gradient(to top, var(--ftr10-tab-border-color) 1px, transparent 1px)',
    '--ftr10-editor-line-number-beam-gradient': 'linear-gradient(90deg, #00f5ff 0%, #7de8ff 40%, #bf00ff 70%, transparent 100%)',
    '--ftr10-tab-active-beam-gradient': 'linear-gradient(90deg, #000a0f 0%, #00f5ff 25%, #7de8ff 50%, #bf00ff 75%, #000a0f 100%)',
    '--ftr10-token-keyword': '#bb9af7',
    '--ftr10-token-string': '#9ece6a',
    '--ftr10-token-number': '#ff9e64',
    '--ftr10-token-comment': '#51597d',
    '--ftr10-token-function': '#7aa2f7',
    '--ftr10-token-operator': '#89ddff',
    '--ftr10-token-boolean': '#ff9e64',
    '--ftr10-token-property': '#7dcfff',
    '--ftr10-token-tag': '#f7768e',
    '--ftr10-token-selector': '#bb9af7',
    ...accentDerived(0, 245, 255)
  }
};

export default popoverUniverse;
