import { ThemePreset, accentDerived } from '../theme-sync';

const classicAtomMaterial: ThemePreset = {
  id: 'classic-atom-material',
  name: 'Atom Material',
  description: 'Material design dark — periwinkle blue on deep teal-grey.',
  colors: ['#82aaff', '#c792ea', '#f07178'],
  overrides: {
    '--ftr10-accent-1': '#82aaffd4',
    '--ftr10-accent-2': '#c792ea',
    '--ftr10-accent-3': '#f07178',
    '--ftr10-accent-4': '#aac4ff',
    '--ftr10-accent-5': '#d0dbff',
    '--ftr10-cyan': '#89ddff',
    '--ftr10-purple': '#c792ea',
    '--ftr10-cursor': '#aac4ff',
    '--ftr10-tab-border-color': '#82aaff',
    '--ftr10-surface-1': '#82aaff26',
    '--ftr10-bg': '#263238ff',
    '--ftr10-bg-editor': '#263238ff',
    '--ftr10-text': '#eeffffde',
    '--ftr10-text-muted': '#eeffff6b',
    '--ftr10-border': '#ffffff14',
    '--ftr10-body-font': "'Victor Mono', monospace",
    '--ftr10-heading-font': "'Space Grotesk', 'Victor Mono', monospace",
    '--ftr10-code-font': "'Victor Mono', monospace",
    '--ftr10-font-activitybar': "'Space Grotesk', monospace",
    '--ftr10-font-sidebar': "'Space Grotesk', monospace",
    '--ftr10-font-panel-bottom': "'Space Grotesk', monospace",
    '--ftr10-font-panel-top': "'JetBrains Mono', monospace",
    '--ftr10-font-auxiliarybar': "'Space Grotesk', monospace",
    '--ftr10-heading-transform': 'none',
    '--ftr10-heading-spacing': '0.3px',
    '--ftr10-radius-block': '10px',
    '--ftr10-radius-quote': '10px',
    '--ftr10-radius-inline': '5px',
    '--ftr10-radius-img': '12px',
    '--ftr10-code-border-l': 'var(--ftr10-border)',
    '--ftr10-code-border-r': 'var(--ftr10-border)',
    '--ftr10-blockquote-border': 'var(--ftr10-border)',
    '--ftr10-strong-color': '#eeffff',
    '--ftr10-em-color': '#82aaff',
    '--ftr10-mark-bg': '#82aaff1a',
    '--ftr10-mark-color': '#c792ea',
    '--ftr10-link-style': 'solid',
    '--ftr10-surface-hover': '#ffffff0a',
    '--ftr10-blockquote-width': '3px',
    '--ftr10-code-scanline': '#00000000',
    '--ftr10-tab-gradient': 'linear-gradient(to top, var(--ftr10-tab-border-color) 1px, transparent 1px)',
    '--ftr10-editor-line-number-beam-gradient': 'linear-gradient(90deg, #82aaff 0%, #aac4ff 40%, #c792ea 70%, transparent 100%)',
    '--ftr10-tab-active-beam-gradient': 'linear-gradient(90deg, #1a222a 0%, #82aaff 25%, #aac4ff 50%, #c792ea 75%, #1a222a 100%)',
    '--ftr10-token-keyword': '#c792ea',
    '--ftr10-token-string': '#c3e88d',
    '--ftr10-token-function': '#82aaff',
    '--ftr10-token-number': '#f78c6c',
    '--ftr10-token-operator': '#89ddff',
    '--ftr10-token-boolean': '#f78c6c',
    '--ftr10-token-property': '#ffcb6b',
    '--ftr10-token-tag': '#f07178',
    '--ftr10-token-selector': '#c792ea',
    '--ftr10-token-comment': '#546e7a',
    ...accentDerived(130, 170, 255)
  }
};

export default classicAtomMaterial;
